name: Hackathon project idea
description: submit a hackathon project idea
project: 
body:
  - type: markdown
    attributes:
      value: |
        # Idea description
        Describe the high-level project idea. Include what the outcome of the hackday could be (a prototype? A polished write-up of an idea?). Make sure to link to relevant resources. 1-2 paragraphs suggested
  - type: markdown
    attributes:
      value: |
        # What skills are needed to tackle the project
        Explain what skills (like writing skills, knowledge about a topic or a technology) would help tackle your project. This helps people find a project where they might be able to help
  - type: checkboxes
    id: terms
    attributes:
      label: Would you be willing to lead this project?
      description: Tick this box if you would be willing to take on this project - alternatively, you can also submit this idea just as is!
      options:
        - label: Yes!
          required: true
