name: Hackday project idea
description: submit a hackday project idea
projects: neuroinformatics-unit/19
body:
  - type: textarea
    id: description
    attributes:
      label: Idea description
      description: Include what the outcome of the hackday could be (a prototype? A polished write-up of an idea?). Make sure to link to relevant resources, and check that the idea doesn't exist yet. You can see all proposed ideas on [this project board](https://github.com/orgs/neuroinformatics-unit/projects/19/views/1).
      placeholder: 1-2 paragraphs suggested.         
  - type: textarea
    id: skills
    attributes:
      label: What skills are needed to tackle the project
      description: Explain what skills (like writing/design skills, knowledge about a topic or a technology) would help tackle your project.
  - type: checkboxes
    id: terms
    attributes:
      label: Would you be willing to lead this project?
      description: Tick this box if you would be willing to take on this project - alternatively, you can also submit this idea just as is!
      options:
        - label: Yes!
          required: false
